# This is a basic workflow to help you get started with Actions

name: Auto-commit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
   #pull_request:
   # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Updating data file
      - name: Updata data.csv file
        run: |
          echo Start Updating data.csv file
          echo -e "[*] Adding current data & time : \n\t$(date)"
          echo $(date +%d/%m/%y,%H:%M,11.5) >> data.csv
          echo -e "[+] Update complete\n"
      
      - name: Auto-commit
        run: |
          echo Start auto-commit
          git config user.name "lostsh-autocommit"
          git config user.email "0pdlna3@gmail.com"
          git add .
          git commit -m "Auto commiting data update"
          git push
          echo [*] Auto-commit complete
