name: Handle data from HTTP

on:
  workflow_dispatch:
    inputs:
      temp:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input Temperature value'
        default: '0'
        required: true
      humidity:
        description: 'Input Humidity value'
        default: '0'
        required: true

jobs:
  write-data:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 #for the auto-commit task
    
    - name: Display data Temperature => [${{ github.event.inputs.temp }}] Humidity => [${{ github.event.inputs.humidity }}]
      run: echo -e "Temperature = ${{ github.event.inputs.temp }}\nHumidity = ${{ github.event.inputs.humidity }}"
    
    - name: Update data.csv 
      run: |
        echo [*] Start Updating data.csv
        echo -e "[*] Adding current data & time : \n\t$(date)"
        echo -e "[*] Adding inputed temperature : \n\t${{ github.event.inputs.temp }}"
        echo -e "[*] Adding inputed humidity : \n\t${{ github.event.inputs.humidity }}"
        echo $(date +%d/%m/%y,%H:%M,${{ github.event.inputs.temp }},${{ github.event.inputs.humidity }}) >> data.csv
        echo -e "[+] Update complete\n"
    
    - name: Auto-commit
      run: |
        echo [*] Start auto-commit
        git config user.name "lostsh-autocommit"
        git config user.email "0pdlna3@gmail.com"
        git add .
        git commit -m "Auto commiting data update"
        git push
        echo [+] Auto-commit complete

# Command to run this task :
#
# curl -X POST \
# -H "Accept: application/vnd.github.v3+json" \
# -H "Authorization: token [personalToken]" \
# https://api.github.com/repos/lostsh/node-time/actions/workflows/manual.yml/dispatches \
# -d '{"ref":"master", "inputs":{"temp":"17.5", "humidity":"89"}}'
#
